// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'


    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
///
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_xI_FYkc-cAJ0AaBvMMK7pLjnuzgyvW0',
    appId: '1:933927264703:web:a2490ae435663a1c2b810a',
    messagingSenderId: '933927264703',
    projectId: 'c2me1-b6d6b',
    authDomain: 'c2me1-b6d6b.firebaseapp.com',
    databaseURL: 'https://c2me1-b6d6b-default-rtdb.firebaseio.com',
    storageBucket: 'c2me1-b6d6b.appspot.com',
    measurementId: 'G-RL536LEYZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKHz11ACBe7gMUJ-BavDGHxQS-mrMuTLE',
    appId: '1:933927264703:android:4e77e5e891b494c62b810a',
    messagingSenderId: '933927264703',
    projectId: 'c2me1-b6d6b',
    databaseURL: 'https://c2me1-b6d6b-default-rtdb.firebaseio.com',
    storageBucket: 'c2me1-b6d6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhSFOTYGnNSTJqCCp6LUh1cHM0Ocvohhw',
    appId: '1:933927264703:ios:08074c11d0df80582b810a',
    messagingSenderId: '933927264703',
    projectId: 'c2me1-b6d6b',
    databaseURL: 'https://c2me1-b6d6b-default-rtdb.firebaseio.com',
    storageBucket: 'c2me1-b6d6b.appspot.com',
    iosClientId: '933927264703-8uq3gnkii29ue0hg20sme4u3grlhp514.apps.googleusercontent.com',
    iosBundleId: 'com.example.c2mealpha1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhSFOTYGnNSTJqCCp6LUh1cHM0Ocvohhw',
    appId: '1:933927264703:ios:08074c11d0df80582b810a',
    messagingSenderId: '933927264703',
    projectId: 'c2me1-b6d6b',
    databaseURL: 'https://c2me1-b6d6b-default-rtdb.firebaseio.com',
    storageBucket: 'c2me1-b6d6b.appspot.com',
    iosClientId: '933927264703-8uq3gnkii29ue0hg20sme4u3grlhp514.apps.googleusercontent.com',
    iosBundleId: 'com.example.c2mealpha1',
  );
}
